# This file is autogenerated and cannot be modified manually.

from __future__ import annotations

from typing import TYPE_CHECKING, Union

if TYPE_CHECKING:
    from catalystwan.versions.v20_15.api_client import ApiClient as ApiClientV20_15

    ApiClient = Union[ApiClientV20_15]

VERSIONS = ["20.15"]


def load_client(version: str):
    if version == "20.15":
        from catalystwan.versions.v20_15.api_client import ApiClient as ApiClientV20_15

        return ApiClientV20_15
    raise RuntimeError("Unsupported version: {}".format(version))
